<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class DemoExtraSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $user = \App\Models\User::where('email', 'demo@example.com')->first();
        if (!$user) return;

        // Add 1 more course (total 5)
        $course = \App\Models\Course::create([
            'user_id' => $user->id,
            'name' => 'Database Systems',
            'code' => 'CS501',
            'color' => '#22c55e',
        ]);

        // Add 13 more tasks
        for ($i = 8; $i <= 20; $i++) {
            $daysOffset = rand(-5, 15);
            $status = $daysOffset < 0 ? (rand(0,1) ? 'completed' : 'overdue') : (rand(0,1) ? 'pending' : 'in_progress');
            
            \App\Models\Task::create([
                'user_id' => $user->id,
                'course_id' => $course->id,
                'title' => 'Task Number ' . $i,
                'description' => 'This is a demo task description for task ' . $i,
                'deadline' => \Carbon\Carbon::now()->addDays($daysOffset)->setHour(12)->setMinute(0),
                'priority' => ['low', 'medium', 'high', 'critical'][rand(0, 3)],
                'status' => $status,
                'progress' => $status === 'completed' ? 100 : rand(0, 80),
                'ai_analysis' => '💡 **AI Analysis**\nThis is an autogenerated analysis for task ' . $i,
                'created_at' => \Carbon\Carbon::now()->subDays(rand(1, 10)),
                'updated_at' => \Carbon\Carbon::now()->subDays(rand(0, 2)),
            ]);
        }

        // Add some sample notifications
        $user->notifications()->create([
            'id' => \Illuminate\Support\Str::uuid(),
            'type' => 'App\Notifications\TaskDeadlineNotification',
            'data' => [
                'type' => 'overdue',
                'title' => 'Task Overdue!',
                'message' => 'Task Number 8 is overdue!',
                'task_id' => 1
            ],
            'read_at' => null,
            'created_at' => now()->subMinutes(15),
            'updated_at' => now()->subMinutes(15),
        ]);
        
        $user->notifications()->create([
            'id' => \Illuminate\Support\Str::uuid(),
            'type' => 'App\Notifications\TaskDeadlineNotification',
            'data' => [
                'type' => 'recommendation',
                'title' => 'AI Suggestion',
                'message' => 'Focus on completing your critical tasks first to improve your score.',
            ],
            'read_at' => null,
            'created_at' => now()->subHours(2),
            'updated_at' => now()->subHours(2),
        ]);
    }
}
